'use strict';

const http   = require('http');
const fs     = require('fs');
const os     = require('os');
const path   = require('path');
const crypto = require('crypto');

// ── Config ────────────────────────────────────────────────────────────────────

const PORT        = 27182;
const HOST        = '127.0.0.1';
const CONFIG_DIR  = path.join(os.homedir(), '.config', 'fde-bridge');
const TOKEN_PATH  = path.join(CONFIG_DIR, 'token');
const CONFIG_PATH = path.join(CONFIG_DIR, 'fde-config.json');
const LOG_FILE    = path.join(CONFIG_DIR, 'server.log');

// Read auth token (generated by install.sh, or created on first run)
let AUTH_TOKEN;
try {
  AUTH_TOKEN = fs.readFileSync(TOKEN_PATH, 'utf8').trim();
} catch {
  AUTH_TOKEN = crypto.randomBytes(32).toString('hex');
  fs.mkdirSync(CONFIG_DIR, { recursive: true });
  fs.writeFileSync(TOKEN_PATH, AUTH_TOKEN, { mode: 0o600 });
}

// ── Logging ───────────────────────────────────────────────────────────────────
// CRITICAL: stdout is reserved for native messaging frames.
// Never write to process.stdout except via writeToExtension().
// All logging goes to stderr and LOG_FILE.

fs.mkdirSync(CONFIG_DIR, { recursive: true });
const logStream = fs.createWriteStream(LOG_FILE, { flags: 'a' });

function log(...args) {
  const line = `[${new Date().toISOString()}] ${args.join(' ')}\n`;
  logStream.write(line);
  process.stderr.write(line);
}

// ── Native messaging I/O ──────────────────────────────────────────────────────
// Protocol: each message is [4-byte LE uint32 length][UTF-8 JSON payload]
// Max message size enforced by Chrome: 1 MB

let extensionConnected = false;
const pendingCallbacks = new Map(); // requestId → { resolve, reject, timer }
let requestCounter = 0;

function genId() {
  return `req_${Date.now()}_${++requestCounter}`;
}

// Read from stdin (messages coming from the Chrome extension via Chrome's NM host runner)
let stdinBuf = Buffer.alloc(0);

process.stdin.on('readable', () => {
  let chunk;
  while (null !== (chunk = process.stdin.read())) {
    stdinBuf = Buffer.concat([stdinBuf, chunk]);
  }
  drainStdin();
});

process.stdin.on('end', () => {
  log('stdin closed — extension disconnected');
  extensionConnected = false;
  for (const [id, { reject, timer }] of pendingCallbacks) {
    clearTimeout(timer);
    reject({ code: 503, message: 'Extension disconnected' });
  }
  pendingCallbacks.clear();
});

function drainStdin() {
  while (stdinBuf.length >= 4) {
    const msgLen = stdinBuf.readUInt32LE(0);
    if (stdinBuf.length < 4 + msgLen) break;

    const msgBytes = stdinBuf.slice(4, 4 + msgLen);
    stdinBuf = stdinBuf.slice(4 + msgLen);

    let msg;
    try {
      msg = JSON.parse(msgBytes.toString('utf8'));
    } catch (e) {
      log('JSON parse error from extension:', e.message);
      continue;
    }

    onExtensionMessage(msg);
  }
}

function onExtensionMessage(msg) {
  log(`← ext: ${JSON.stringify(msg).slice(0, 300)}`);

  switch (msg.type) {
    case 'ping':
      writeToExtension({ type: 'pong' });
      break;

    case 'pong':
      break;

    case 'tab_status':
      extensionConnected = true;
      break;

    case 'response': {
      const cb = pendingCallbacks.get(msg.requestId);
      if (!cb) {
        log('Unknown requestId in response:', msg.requestId);
        break;
      }
      pendingCallbacks.delete(msg.requestId);
      clearTimeout(cb.timer);
      if (msg.error) {
        cb.reject(msg.error);
      } else {
        cb.resolve(msg.result);
      }
      break;
    }

    default:
      log('Unknown message type from extension:', msg.type);
  }
}

function writeToExtension(msg) {
  const json = JSON.stringify(msg);
  const payload = Buffer.from(json, 'utf8');
  if (payload.length > 1024 * 1024) {
    log('Message too large to send to extension:', payload.length);
    return;
  }
  const header = Buffer.alloc(4);
  header.writeUInt32LE(payload.length, 0);
  process.stdout.write(Buffer.concat([header, payload]));
  log(`→ ext: ${json.slice(0, 300)}`);
}

// ── HTTP server ───────────────────────────────────────────────────────────────

const server = http.createServer((req, res) => {
  res.setHeader('Content-Type', 'application/json');

  // Only allow loopback connections (belt-and-suspenders on top of bind address)
  const remoteAddr = req.socket.remoteAddress;
  if (remoteAddr !== '127.0.0.1' && remoteAddr !== '::1' && remoteAddr !== '::ffff:127.0.0.1') {
    res.writeHead(403);
    res.end(JSON.stringify({ error: 'Forbidden: loopback only' }));
    return;
  }

  // Auth check
  const token = req.headers['x-fde-token'];
  if (token !== AUTH_TOKEN) {
    res.writeHead(401);
    res.end(JSON.stringify({ error: 'Invalid or missing X-FDE-Token header' }));
    return;
  }

  if (req.method === 'GET' && req.url === '/health') {
    res.writeHead(200);
    res.end(JSON.stringify({ ok: true, extensionConnected }));
    return;
  }

  if (req.method === 'POST' && req.url === '/fde') {
    if (!extensionConnected) {
      res.writeHead(503);
      res.end(JSON.stringify({
        error: 'Extension not connected. Ensure the FDE Bridge extension is installed and a Foundry tab is open.',
        reconnectHint: 'Open a Foundry tab and wait a few seconds for the content script to register.',
      }));
      return;
    }

    let body = '';
    req.on('data', d => { body += d; });
    req.on('end', async () => {
      let payload;
      try {
        payload = JSON.parse(body);
      } catch {
        res.writeHead(400);
        res.end(JSON.stringify({ error: 'Invalid JSON body' }));
        return;
      }

      if (!payload.prompt || typeof payload.prompt !== 'string') {
        res.writeHead(400);
        res.end(JSON.stringify({ error: 'Missing required field: prompt (string)' }));
        return;
      }

      const requestId = genId();
      const timeoutMs = typeof payload.timeout_ms === 'number' ? payload.timeout_ms : 300_000;

      // Sync config override to extension storage if provided
      if (payload.config_override) {
        writeToExtension({ type: 'config_sync', config: payload.config_override });
      }

      // Forward request to extension
      writeToExtension({
        type: 'request',
        requestId,
        payload: {
          prompt:          payload.prompt,
          new_session:     payload.new_session === true,
          config_override: payload.config_override ?? null,
          timeout_ms:      timeoutMs,
        },
      });

      // Wait for response
      try {
        const result = await new Promise((resolve, reject) => {
          // +5s buffer beyond content script timeout
          const timer = setTimeout(() => {
            pendingCallbacks.delete(requestId);
            reject({ code: 408, message: 'Timeout waiting for FDE response' });
          }, timeoutMs + 5000);

          pendingCallbacks.set(requestId, { resolve, reject, timer });
        });

        res.writeHead(200);
        res.end(JSON.stringify({ ok: true, response: result.response }));
      } catch (err) {
        const code = err.code ?? 500;
        res.writeHead(code);
        res.end(JSON.stringify({
          error:   err.message ?? String(err),
          partial: err.partial ?? null,
        }));
      }
    });
    return;
  }

  res.writeHead(404);
  res.end(JSON.stringify({ error: 'Not found' }));
});

server.listen(PORT, HOST, () => {
  log(`FDE Bridge HTTP server listening on http://${HOST}:${PORT}`);

  // Send handshake — confirms host is alive and syncs auth token
  writeToExtension({ type: 'handshake', token: AUTH_TOKEN });
  extensionConnected = true; // Optimistic; confirmed on first 'tab_status' message

  // Sync stored config to extension on startup if config file exists
  try {
    const config = JSON.parse(fs.readFileSync(CONFIG_PATH, 'utf8'));
    writeToExtension({ type: 'config_sync', config });
    log('Synced config from', CONFIG_PATH);
  } catch {
    // Config file is optional
  }
});

server.on('error', (err) => {
  if (err.code === 'EADDRINUSE') {
    log(`Port ${PORT} already in use. Another instance of the native host may be running.`);
  } else {
    log('HTTP server error:', err.message);
  }
  process.exit(1);
});

process.on('uncaughtException', (e) => log('uncaughtException:', e.stack));
process.on('unhandledRejection', (e) => log('unhandledRejection:', String(e)));
